services:
  dropbox:
    image: otherguy/dropbox
    container_name: dropbox
    restart: unless-stopped
    environment:
      TZ: Europe/London
      DROPBOX_UID: 1000
      DROPBOX_GID: 1000
    volumes:
      - /var/media/Dropbox:/dropbox
      - dropbox-config:/config

volumes:
  dropbox-config:
